---

- hosts: localhost

# GET Quote of the Day API #
  tasks:
    - name: Test API
      uri:
        url: https://quotes.rest/qod
        headers: 
          Accept-Encoding: gzip, deflate, br
          Connection: keep-alive
        method: GET
        return_content: yes
        body_format: json
      register: QuoteoftheDay
      
# Print Quote of the Day #
    - debug:
        msg: "{{ QuoteoftheDay }}"