---

- hosts: localhost

# GET Quote of the Day API #
  tasks:
    - name: Get Quote of the Day from API
      uri:
        url: https://quotes.rest/qod
        headers: 
          Accept-Encoding: gzip, deflate, br
          Connection: keep-alive
        method: GET
        return_content: yes
        body_format: json
      register: QuoteoftheDay

# Print Quote of the Day #
    - debug:
        msg: "{{ QuoteoftheDay }}"

# Save RAW Response to file #
    - name: Save Full Response to JSON file
      copy: content="{{ QuoteoftheDay }}" dest=../quotes/FullResponseQuoteoftheDay_{{ ansible_date_time.date }}.json

# Save Only Quote to Text File # 
    - name: Save Quote to File 
      copy: content="{{ QuoteoftheDay.json.contents.quotes }}" dest=../quotes/QuoteOfTheDay_{{ ansible_date_time.date }}.txt

# Save Nice YAML RAW Response to file #
    - name: Save Nice YAML Full Response to YAML file
      copy: content="{{ QuoteoftheDay | to_nice_yaml }}" dest=../quotes/FullResponseQuoteoftheDay_{{ ansible_date_time.date }}.yml

# Save Nice JSON RAW Response to file #
    - name: Save Nice JSON Full Response to JSON file
      copy: content="{{ QuoteoftheDay | to_nice_yaml }}" dest=../quotes/EasyToReadFullResponseQuoteoftheDay_{{ ansible_date_time.date }}.yml